"use client";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

type TrainingPlanDisplayProps = {
  plan: string;
  onReset: () => void;
};

export function TrainingPlanDisplay({ plan, onReset }: TrainingPlanDisplayProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Your Personalized Training Plan</CardTitle>
        <CardDescription>
          Here is the plan generated by our AI coach. You can log your workouts
          from the &quot;Log Workout&quot; page.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="prose prose-sm dark:prose-invert max-w-none p-4 bg-muted rounded-md">
            <pre className="whitespace-pre-wrap bg-transparent p-0 font-sans text-sm">
                {plan}
            </pre>
        </div>
        <Button onClick={onReset} variant="outline">
          Generate a New Plan
        </Button>
      </CardContent>
    </Card>
  );
}
